### ISSUE TITLE
Keep initial expiration after an update

### ISSUE THREAD

**Issue by cterrazas2** [Attumm/redis-dict#23]
If I update `dic['gone']` before the sixty seconds below, the initial `expire_at` below is lost for this key. Is this intentional? If so, how would I achieve keeping the initial expire on the key?

```python3
from redis_dict import RedisDict

dic = RedisDict(namespace='bar')

seconds = 60
with dic.expire_at(seconds):
    dic['gone'] = 'in sixty seconds'

# update before 60 seconds and initial expire is gone
dic['gone'] = "new value"
```

**Comment by Attumm** [comment]
Hi @cterrazas2,

Currently, `redisDict` supports both global expiration and the temporary expiration, as illustrated in your example.

**Global Expiration:**
```python
dic = RedisDict(namespace='bar', expire=5)

seconds = 60
with dic.expire_at(seconds):
    dic['gone'] = 'in sixty seconds'
```

**Temporary Expiration:**
```python
dic = RedisDict(namespace='bar')

seconds = 60
with dic.expire_at(seconds):
    dic['gone'] = 'in sixty seconds'
```

It is possible to encapsulate the temporary expiration within a function for ease of use. For example:
```python
def store_with_expiration(dic, key, value, expiration_time=20):
    with dic.expire_at(expiration_time):
        dic[key] = value
```
Usage:
```python
store_with_expiration(dic, 'my_key', 'my_value', 20) # This will be gone in twenty seconds
```

However, if you could provide more details regarding your specific use case, it could be a new feature:)

**Comment by cterrazas2** [comment]
Yeah so the use case would be to preserve temporary expiration for a specific key, even if that key is updated. Right now, it looks like `self.expire` is temporarily overridden and then set back to its original value [here](https://github.com/Attumm/redis-dict/blob/main/redis_dict.py#L645-L647). So it would be nice to have something like an extra arg to `expire_at` like below:

```python3
from redis_dict import RedisDict

dic = RedisDict(namespace='bar')

seconds = 60
with dic.expire_at(seconds, preserve_expiration=True):
    dic['gone'] = 'in sixty seconds'

# update before 60 seconds, but the initial 60 seconds is still preserved
# for this key rather than using the global expiration.
dic['gone'] = "new value"
```

**Comment by cterrazas2** [comment]
I think the simplified approach makes sense and keep the expiration rules isolated per instance. Right now the only thing used to track expiration is the `self.expired`. Another field could be added for temporary expirations, but that might be cumbersome to maintain. There is a `KEEPTTL` command in redis that might make sense to use in this feature.

**Comment by Attumm** [comment]
So, would it be acceptable if the expiration was set on a per-session basis?

For instance:

```python
with dic.expire_at(seconds, preserve_expiration=True):
    dic['gone'] = 'in sixty seconds'
```

Additionally, to make it more consistent and permanent, we could use a configuration that can be stored for other instances, like so:
```python
    dic = RedisDict(namespace='bar', expire_key_at={"mykey": 10})
```
This approach would allow the expiration to work during the session in which RedisDict is active. With the added configuration, it can also be made persistent across different instances.
Thus we would gain solve some of distributed computing issues.

Would this solution solve your use case?

**Comment by cterrazas2** [comment]
@Attumm yes, that looks like it would work for my use case.

**Comment by Attumm** [comment]
Hi, I have made an update to the code at the following link:

[GitHub Commit](https://github.com/Attumm/redis-dict/commit/e38f1bf7c473483983e0e621987d79899b0b29bd)

Could you please review it to see if it addresses your use case? While implementing these changes, I encountered some edge cases that proved to be quite challenging. Perhaps the solution will become obvious eventually, but at the moment, it escapes me.

Consider the following code:

```python
with dic.expire_at(seconds, preserve_expiration=True):
    dic['gone'] = 'in sixty seconds'
```

The issue here is that this line will alter the state of `redis_dict`. However, what if the code is executed in another branch? For instance:

```python
if foo:
    with dic.expire_at(seconds, preserve_expiration=True):
        dic['gone'] = 'in sixty seconds'
```

In this scenario, the configuration of `redis_dict` will be changed conditionally, which could lead to errors later on. I'm not yet sure what the correct approach to resolve this is, but we can work together to find a solution. Off-course the example is simplified but within a codebase, and a few refactors it's likely scenario. 

In the meantime, I did added the  "expire_key" as config.

```python
redis_dic = self.create_redis_dict(expire=3600, expire_key={"foo": expected})
```

If this does not address your use case, we might need to go back to the drawing board. Please let me know your thoughts. Keep in mind that distributed computing can be quite complex. The goal of the project is trying to sidestep the issues as much as possible.

**Comment by cterrazas2** [comment]
Yeah I think the first code is more my use case. The keys and expirations will be generated "on the fly", so I can't just set it in the initial creation of a redis_dict instance. What if instead we move the `preserve_expiration` in the creation of an instance? Then, both global and temporary expirations will keep their initial expirations set. For example:

```python3
redis_dict = RedisDict(namespace="app", expire=3600, preserve_expiration=True)
```
Then with this configuration, whenever a key first has an expiration set on it, we just keep it until it's lifetime? So, in the `_store` method you could have:

```python3
def _store(self, key: str, value: Any) -> None:
    ...
    # check if key exists and preserve_expiration set
    if self.redis.exists(key) and self.preserve_expiration:
        self.redis.set(self._format_key(key), store_value, keepttl=True)
    else:
        self.redis.set(self._format_key(key), store_value, ex=self.expire)
```

**Comment by Attumm** [comment]
I appreciate the concept and it looks like that could be the final candidate., but I've identified three concerns, two of which I believe can be addressed by me.
The third one is a question to you.

1. The current implementation would add an extra round trip to Redis for all use cases due to the check for key existence. We could mitigate this by reordering the conditions:

```python
if self.preserve_expiration and self.redis.exists(key):
```

2. The `keepttl` feature is only available in Redis version 6.0.0 and above. We can address this by ensuring that if `self.preserve_expiration` is set to `True`, the Redis version is 6.0.0 or higher. This check can be performed during initialization.

3. I would like to confirm if implementing this change alone would resolve the issue you're facing. In other words, is the remainder of the MR (Merge Request) code still necessary?
If not, I'll remove the changes from yesterday.

Does the code that you shared solve all your use cases?
If so then we go with this approach:)

```python
redis_dict = RedisDict(namespace="app", expire=3600, preserve_expiration=True)

def _store(self, key: str, value: Any) -> None:
    ...
    # Check if the key exists and preserve_expiration is set
    if self.preserve_expiration and self.redis.exists(key):
        self.redis.set(self._format_key(key), store_value, keepttl=True)
    else:
        self.redis.set(self._format_key(key), store_value, ex=self.expire)
```

**Comment by cterrazas2** [comment]
You can remove the rest of the code from your PR. Here's a code snippet that is backwards compatible, and should work until you update to redis 6.0.0 for `keepttl`. It fits all of my use cases:

```python3
redis_dict = RedisDict(namespace="app", expire=3600, preserve_expiration=True)

def _store(self, key: str, value: Any) -> None:
    ...
    formatted_key = self._format_key(key)
    # Check if the key exists and preserve_expiration is set
    if self.preserve_expiration and self.redis.exists(formatted_key):
        self.redis.set(formatted_key, store_value, ex=self.redis.ttl(formatted_key))
    else:
        self.redis.set(formatted_key, store_value, ex=self.expire)
```

**Comment by Attumm** [comment]
Many thanks. I have thoroughly tested it and found that using 'keepttl' would indeed be the better choice, primarily due to the potential distributed computing issues that might arise, particularly around corner cases. For instance, if we were to get an expiration and then set it again, the rounding off of seconds would interfere with redis ttl. Therefore, the 'keepttl' approach you suggested in the beginning is the more robust solution.

These issues were discovered during the testing phase, which was rather time-consuming.

https://github.com/Attumm/redis-dict/releases/tag/v2.1.0

**Comment by cterrazas2** [comment]
Awesome, thanks for adding this feature!
